apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    name: longhorn
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ingress
  namespace: argocd
  labels:
    name: longhorn-ingress
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/manifests/longhorn-ingress
    repoURL: https://github.com/team-shahu/shahu-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
  labels:
    name: traefik-ingress
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/manifests/traefik-ingress
    repoURL: https://github.com/team-shahu/shahu-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-system
  namespace: argocd
  labels:
    name: cnpg-system
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: cnpg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shahu-ski
  namespace: argocd
  labels:
    name: shahu-ski
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/manifests/shahu-ski
    repoURL: https://github.com/team-shahu/shahu-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---
